#!/bin/bash

# Ellem Groups Website - Quick Reference Commands

echo "🚀 Ellem Groups Website - Quick Reference"
echo "=========================================="
echo ""
echo "📁 Project Location:"
echo "   /Users/gunasekaran/Desktop/ellem-groups-website"
echo ""
echo "🔧 Development Commands:"
echo "   npm install          # Install dependencies"
echo "   npm run dev          # Start development server (http://localhost:3000)"
echo "   npm run build        # Build for production"
echo "   npm start            # Start production server"
echo "   npm run lint         # Check code quality"
echo ""
echo "📄 Documentation:"
echo "   README.md            # Full documentation"
echo "   GETTING_STARTED.md   # Quick start guide"
echo "   DEPLOYMENT.md        # Deployment instructions"
echo ""
echo "🎨 Key Files to Customize:"
echo "   app/contact/page.tsx       # Update contact info"
echo "   app/foundry/page.tsx       # Update Foundry details"
echo "   app/engineering/page.tsx   # Update Engineering details"
echo "   app/fluid-control/page.tsx # Update Fluid Control details"
echo "   components/Footer.tsx      # Update footer & social links"
echo "   styles/globals.css         # Customize colors"
echo ""
echo "📸 Add Images To:"
echo "   public/                    # Create this folder for images"
echo ""
echo "🌐 Deployment:"
echo "   See DEPLOYMENT.md for full instructions"
echo "   Recommended: Vercel.com (easiest for Next.js)"
echo ""
echo "✨ Features Included:"
echo "   ✓ Homepage with hero section"
echo "   ✓ Company pages (Foundry, Engineering, Fluid Control)"
echo "   ✓ Contact page with form"
echo "   ✓ About page"
echo "   ✓ Mobile responsive design"
echo "   ✓ SEO optimized"
echo "   ✓ Professional branding"
echo ""
echo "🎯 Next Steps:"
echo "   1. cd /Users/gunasekaran/Desktop/ellem-groups-website"
echo "   2. npm install"
echo "   3. npm run dev"
echo "   4. Open http://localhost:3000 in browser"
echo "   5. Customize content with your information"
echo "   6. Add company images"
echo "   7. Deploy to ellemgroups.com"
echo ""
